name: 'Pull Request - Label Check'

on:
  workflow_call:

jobs:
  check-labels:
    name: 'Check Labels'
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mheap/github-action-required-labels@v3
        with:
          mode: exactly
          count: 1
          labels: "version:none, version:patch, version:minor, version:major"
          add_comment: true
          message: "This PR is blocked from merging due to a missing `version:` Label or multiple `version:` Labels being applied"