name: 'Pull Request - Open'

on:
  workflow_call:

jobs:
  add-comment:
    name: 'Add Comment'
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: "Check Labels not Applied"
        id: checkLabels
        uses: mheap/github-action-required-labels@v3
        with:
          mode: exactly
          count: 0
          labels: "version:none, version:patch, version:minor, version:major"
          exit_type: success
      
      - name: "Add a PR Comment"
        if: ${{ steps.checkLabels.outputs.status == 'success' }}
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            Please apply a Versioning Label of `version:major`, `version:minor` or `version:patch` to have this PR Released after Merging.

            If you do not wish to Bump the Project Version and Release, then apply the `version:none` Label.